name: build_sqlite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Download source
        run: git clone https://github.com/sqlite/sqlite.git --branch version-3.36.0

      - name: Install Tcl on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install tcl

      - name: Build for Unix
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          mkdir bld
          cd bld
          ../sqlite/configure
          make
          make sqlite3.c
          make test
