name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.x'

      - name: Check Formatting
        run: deno fmt --check -c deno.json

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.x'

      - name: Check Formatting
        run: deno lint -c deno.json

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install SQLite3 on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt install sqlite3

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'canary'

      - name: Run Tests
        run: deno test --unstable -A test/test.ts